language: node_js
node_js:
  - lts/*
cache: npm
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: "4cckt59ukcN0gPVX66QLw1R1dx4S8e1p3t1K2yzNA1WJK2UqwznkcaZd2+GmpNkI"
