language: node_js
node_js:
  - lts/*
cache: npm
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: "9aa17913-f16e-4e94-81c9-767f737c3d21"
